name: branch
on:
  push:
    branches-ignore:
      - master

jobs:
  build-and-push-branch:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            BASE_REPO=mcr.microsoft.com/dotnet/core
            BASE_TAG=3.1
          tags: ghcr.io/formit-io/dotnet-core:3-1-beta
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}