name: branch
on:
  push:
    branches:
      - master
    tags:
      - 3.1-*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      BASE_REPO: mcr.microsoft.com/dotnet/core
      BASE_TAG: 3.1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            BASE_REPO=$BASE_REPO
            BASE_TAG=$BASE_TAG
          tags: |
            ghcr.io/formit-io/dotnet-core:$GITHUB_REF
            ghcr.io/formit-io/dotnet-core:3-1-latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}